# Generated by Django 4.2.11 on 2024-04-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_status',
            field=models.CharField(choices=[('', ''), ('pending', 'pending'), ('completed', 'complete')], default='', max_length=100),
        ),
    ]
